{"uuid": "7219dc12-bebf-4062-9ac9-9225ad968550", "children": ["e4812358-0535-4b60-90f4-02bde04e8c84"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A8069/web/login&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A8069.\n\n", "trace": "  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\tests\\conftest.py\", line 16, in setup\n    driver = BrowserInitialization.generateDriver(request.param, TestData.BASE_URL)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\utilities\\BrowserInitialization.py\", line 18, in generateDriver\n    driver.get(url)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1619084601943, "stop": 1619084617276}], "start": 1619084601943, "stop": 1619084617461}